# Generated by Django 5.0.7 on 2024-11-19 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteriaApp', '0002_categoria_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_ilimitado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
