# Generated by Django 5.0.7 on 2024-12-08 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteriaApp', '0003_producto_stock_ilimitado_alter_producto_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='calle_direccion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='calle_numero',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nombre',
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado_compra',
            field=models.CharField(default='Pendiente', max_length=50),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado_pedido',
            field=models.CharField(default='Preparando', max_length=50),
        ),
        migrations.AddField(
            model_name='cliente',
            name='productos_carro',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='cliente',
            name='total_pagar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
