# Generated by Django 5.0.7 on 2024-12-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteriaApp', '0004_remove_cliente_apellido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rut',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
