# Generated by Django 5.0.7 on 2024-12-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteriaApp', '0005_cliente_direccion_cliente_rut_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='alertas',
            field=models.CharField(choices=[('todos', 'Pedidos y Promociones'), ('pedidos', 'Solo pedidos'), ('promociones', 'Solo promociones')], default='todos', max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='motivo_eliminacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='notificaciones_correo',
            field=models.BooleanField(default=True),
        ),
    ]
