# Generated by Django 5.0.7 on 2024-12-08 20:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteriaApp', '0006_cliente_alertas_cliente_motivo_eliminacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='fk_menu',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='fk_cliente',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='fk_orden',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='cod_orden',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='estado_orden',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='fk_cliente',
        ),
        migrations.AddField(
            model_name='orden',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orden',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cafeteriaApp.cliente'),
        ),
        migrations.AddField(
            model_name='orden',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='orden',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cafeteriaApp.producto'),
        ),
        migrations.AddField(
            model_name='orden',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password_usuario',
            field=models.CharField(default='12345678', max_length=8),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('cajero', 'Cajero'), ('cocinero', 'Cocinero')], default='cajero', max_length=10),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
