# Generated by Django 5.0.7 on 2024-12-10 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteriaApp', '0009_remove_carrito_cliente_remove_carrito_subtotal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='estado_compra',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado')], default='pendiente', max_length=50),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado_pedido',
            field=models.CharField(choices=[('procesando', 'Procesando'), ('enviado', 'Enviado'), ('entregado', 'Entregado')], default='procesando', max_length=50),
        ),
        migrations.AddField(
            model_name='cliente',
            name='total_pagar',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(blank=True, default='Sin descripción'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(blank=True, default='Sin dirección'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(blank=True, default='Sin RUT', max_length=12),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, default='Sin teléfono', max_length=15),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, default='Sin descripción'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='spinneritem',
            name='description',
            field=models.TextField(blank=True, default='Sin descripción'),
        ),
        migrations.AlterField(
            model_name='spinneritem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='spinner_images/'),
        ),
        migrations.AlterField(
            model_name='spinneritem',
            name='title',
            field=models.CharField(default='Sin título', max_length=100),
        ),
    ]
