# Generated by Django 5.0.7 on 2024-12-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteriaApp', '0011_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpinnerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='spinner_images/')),
                ('width', models.PositiveIntegerField(default=300)),
                ('height', models.PositiveIntegerField(default=300)),
            ],
        ),
        migrations.DeleteModel(
            name='SpinnerItem',
        ),
    ]
