# Generated by Django 5.0.7 on 2024-12-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteriaApp', '0012_spinnerimage_delete_spinneritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('proceso', 'En Proceso'), ('camino', 'En Camino'), ('entregado', 'Entregado')], default='proceso', max_length=20),
        ),
    ]
