# Generated by Django 5.0.7 on 2024-12-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteriaApp', '0015_alter_cliente_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(default='Sin RUT', max_length=12, null=True),
        ),
    ]
